version: '3.8'

services:
  # Node.js application service
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - app-network

  # MongoDB service
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db # Volume for persisting MongoDB data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
